### ISSUE TITLE
Script does not see "sda1" partition

### ISSUE THREAD

**Issue by Arsezar** [seokbeomKim/rofi-mount-menu#1]
Good evening.
I have tried to use this script and everything worked except one thing, it does not see "sda1", which is my connected USB flash drive, script only sees my windows partitions. Did I miss something? Thank you in advance.
lsblk output:
❯ lsblk
NAME                  MAJ:MIN  RM         SIZE   RO   TYPE      MOUNTPOINTS
sda                            8:0           1      57.3G      0    disk 
└─sda1                  8:1           1      57.3G      0    part 
nvme0n1             259:0           0    476.9G      0    disk 
├─nvme0n1p1 259:1           0      100M      0   part        /boot/efi
├─nvme0n1p2 259:2           0        16M      0   part 
├─nvme0n1p3 259:3           0    233.6G     0   part 
├─nvme0n1p4 259:4           0       674M     0   part 
├─nvme0n1p5 259:5           0       58.6G     0   part 
├─nvme0n1p6 259:6           0     155.5G     0  part        /
└─nvme0n1p7 259:7           0       28.4G     0  part        [SWAP]

**Comment by Arsezar** [comment]
I figured out what the problem was. My USB did not have label so it did not appear in **/dev/disk/by-label** and if someone has problems with mounting, you need to create a file with sudo password, 31 and 62 lines in script:
`SUDO_ASKPASS=/home/sukbeom/.local/bin/sudo_pass sudo -A mount /dev/$DNODE $MOUNT_DIRECTORY/$DNAME -o umask=000 && notify-send "$DNAME is mounted at $MOUNT_DIR"`
`SUDO_ASKPASS=/home/sukbeom/.local/bin/sudo_pass sudo -A umount $MOUNT_DIR && notify-send "$MOUNT_DIR is umounted"`
Or instead you can use **qsudo** (GUI for sudo). Link - https://github.com/sr-tream/qsudo. There is my solution:
`$QSUDO mount /dev/$DNODE $MOUNT_DIRECTORY/$DNAME -o umask=000 && notify-send "$DNAME is mounted at $MOUNT_DIR"`
`$QSUDO umount $MOUNT_DIR && notify-send "$MOUNT_DIR is umounted"`
**$QSUDO** is my environment variable in **.bash_profile**, also I added it in **.zshenv** just in case:
`export QSUDO="/home/<username>/Repos/qsudo-build/qsudo"`.
And of course if you are not using **urxvt**, you should delete line 32:
`urxvt -e ranger ${MOUNT_DIR}`

**Comment by seokbeomKim** [comment]
Thanks for sharing. :)
